# -*- coding: utf-8 -*-
"""Endpoint with a cyclic start.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lx7GRDi4103UWRpGhkheUajPm4rOENS7
"""

import networkx as nx
import numpy as np
import random
import matplotlib.pyplot as plt
import operator

number_of_vertices=int(input("enter number of vertices of graph:"))
probability=0.6
number_of_simulations=int(input("enter number of simulations to be carried out:"))
Approx_Rank_Vector=[0]*number_of_vertices

graph=nx.gnp_random_graph(number_of_vertices,probability,directed=True)
matrix=nx.to_numpy_matrix(graph)
print("--------------------Adjacency Matrix----------------------------\n")

print(matrix)
print("------------------------------------------------\n")
print("------------------------Random Graph Genrated------------------------\n")
nx.draw(graph,with_labels=True)
plt.show()

print("------------------------------------------------\n")


def outlinks(lst):
  c=0
  lst1=[]
  for i in range(number_of_vertices):
    if lst[0,i]!=0:
      c=c+1
      lst1.append(i)
  return c,lst1
  
  
for i in range(number_of_vertices):
  for i in range(number_of_simulations):
    node_random=random.choice([i for i in range(graph.number_of_nodes())])
    while(1):
      probability=random.uniform(0,1)
      if probability < 0.85:
        break
      else:
        number_of_outlinks,lst = outlinks(matrix[node_random])
      
        if number_of_outlinks>0 :

          node_random=random.choice([i for i in lst])

        else:
          node_random=random.choice([i for i in range(graph.number_of_nodes())])
    Approx_Rank_Vector[node_random]=Approx_Rank_Vector[node_random]+1
       
Final_Rank_Vector=[(i/(number_of_vertices*number_of_simulations)) for i in Approx_Rank_Vector]

print("----------------------Aproxx Final Rank vector--------------------------\n")
print(Final_Rank_Vector)

print("------------------------------------------------\n")

for i in range(len(Final_Rank_Vector)):
  print("rank of page",i,"is",Final_Rank_Vector[i])